build.xml
This fixes the Ant build so that it actually works (AFAICT; with the resulting JAR, `java -jar css-validator.jar http://www.w3.org/` doesn't throw any exceptions and it outputs a reasonable-looking CSS validation errors report).
=> Improving the build: Step 1: Fix the Ant build

build.xml
No point in downloading the samples, docs, and other JARs that we don't use.
=> Grab only the Xerces JARs instead of the entire distribution tarball

DOWNLOAD.html.fr
Mostly about how to install from Git, not CVS. The changed are based on the  `DOWNLOAD.html.en` file.
It can confuse or discourage people finding that they would be supposed to use CVS even if a Git repository exists!
If there is more documentation to update in English or French (native language) I volunteer for it.
=> Updated the french documentation from the english one

.gitignore
=> Do not track Java package files

org/w3c/css/util/Util.java
`Util.isWhiteSpace` returns `true` if the character **is** whitespace. The current documentation of `Util.isWhiteSpace` doesn't match its implementation.
=> Fix documentation for Util.isWhiteSpace

org/w3c/css/servlet/CssValidator.java
To enable scripted access to the CSS validator from frontend JavaScript code
running in a browser, this change makes the CSS validator send back the
necessary Access-Control-Allow-Origin, Access-Control-Allow-Headers,
Access-Control-Allow-Methods, and Access-Control-Max-Age response headers.
See https://stackoverflow.com/q/46855633/441757
=> Add CORS headers for scripted cross-origin access

build.xml
This change adds includeantruntime="false" to the attributes for the
javac element in the ant build.xml file, in order to prevent a build
warning that otherwise gets emitted.
=> Add includeantruntime="false" to javac build attrs

DOWNLOAD.html.en, build.xml
This change makes the built css-validator.jar file also include all dependency
jars from the lib/ subdirectory. That makes it possible to actually run the jar
file with just `java -jar css-validator.jar ...`, without any other jars needing
to be present in the local environment.
Fixes https://github.com/w3c/css-validator/issues/45
=> Make css-validator.jar include all dependencies

org/w3c/css/media/AtRuleMedia.java
This change makes `org.w3c.css.media.AtRuleMedia.getInstance` handle all current
`CssVersion` cases, and to throw for unrecognized cases.
Previously, calling `org.w3c.css.media.AtRuleMedia.getInstance` with an unhandled
`CssVersion` value caused it to return `null` instead of an expected `AtRuleMedia`
instance — which in turn caused a `NullPointerException` to get thrown in
`org.w3c.css.parser.analyzer.CssParser.mediaquery`, which tries to call
`org.w3c.css.media.AtRuleMedia.addMedia` on the expected `AtRuleMedia` instance.
=> Handle all CssVersion cases in AtRuleMedia

org/w3c/css/util/ApplContext.java, org/w3c/css/util/HTTPURL.java, org/w3c/css/util/UnicodeInputStream.java
This change adds a copy of the org.apache.velocity.io.UnicodeInputStream source
from the https://svn.apache.org/repos/asf/velocity/engine repo, changing the
package name to org.w3c.css.util, and updating ApplContext and HTTPURL to rely
on it instead of importing org.apache.velocity.io.UnicodeInputStream.
The rationale for this change is, it allows the CSS validator to be integrated
into other applications without any dependency on Apache Velocity (the jar
distro for which is 439K…). Specifically in the case of the Nu Html Checker, it
allows the CSS validator to be integrated without needing any new dependencies
at to be added to the existing Nu Html Checker dependency set.
=> Add org.apache.velocity.io.UnicodeInputStream copy

build.xml
The ant “jar” target in build.xml here now builds a css-validator.jar file that
includes all the dependency jars from the lib/ subdirectory.  But in some cases
it’s also still useful to have a css-validator.jar without the dependencies; so
this change adds an additional “jar-without-dependencies” target for doing that.
=> Add target to build jar with no dependency jars

org/w3c/css/util/Messages.properties.en
This changes the following error message:
> Sorry, the at-rule %s is not implemented.
...to this:
> Unrecognized at-rule %s
---
We don’t need the word “Sorry” in there, and the “is not implemented” part
makes users wonder if it means the at-rule isn’t implemented in browsers.
So let’s just make it “Unrecognized” — which covers both the cases of a valid
at-rule like @supports, which the CSS Validator doesn’t yet recognize because
no support for it has been added to the validator yet, and also the case of a
completely invalid at-rule like @key-frames, which is typo for @keyframes.
=> Refine message for unrecognized at-rule

org/w3c/css/css/HTMLParserStyleSheetHandler.java, org/w3c/css/css/TagSoupStyleSheetHandler.java, org/w3c/css/util/Messages.properties.en
Per [current requirements in the HTML spec](https://goo.gl/rpW3h2):
> Authors should not specify a `type` attribute on a `style` element.
Addresses https://github.com/validator/validator/issues/584
=> Drop warning about missing style[type] attribute

org/w3c/css/css/CssValidator.java
This change causes the parameter info for the ApplContext instance when using
the command-line interface to get dumped to stderr instead of stdout — so if you
redirect stdout to a file/pipe, you get just the actual error/warning report.
That ensures the resulting report output is syntactically-correct HTML (for
output=html), valid JSON (for output=json), etc. — without a prolog like:
```
{output=json, profile=css3, vextwarning=false, warning=2, medium=all, lang=en}
```
=> Emit params to stderr, not stdout, when using CLI

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/util/Messages.properties.en
This change makes the checker handle at-rules such as @-ms-viewport and
@-webkit-keyframes as vendor extensions — which means, if the checker is
run with the option to treat vendor extension as warnings, the messages
for those cases are now emitted as warnings instead of as errors.
=> Treat starts-with-dash at rules as vendor-prefixed

build.xml, org/w3c/css/css/StyleSheetGenerator.java
This change makes it possible to run the css-validator.jar CLI from anywhere.
Prior to this change, the css-validator.jar CLI could be run only from within a
working directory that had the org/w3c/css/css/*.properties Velocity templates.
That’s because the code for the CLI looked for the templates on the filesystem,
or looked for a jar on the filesystem containing the templates.
This change makes the CLI code instead just look for the templates anywhere in
the classpath. And the templates are in the css-validator.jar file, so it works
regardless of whether you invoke the CLI with `java -jar css-validator.jar` or
instead with `java -cp css-validator.jar org.w3c.css.css.CssValidator`.
This change also makes the CLI stop looking for the dependency jar files on the
filesystem in a `lib/` …
=> Make css-validator.jar CLI runnable anywhere

org/w3c/css/properties/CSS3Properties.properties, org/w3c/css/properties/CSS3SVGProperties.properties, org/w3c/css/properties/Media.properties, org/w3c/css/properties/css/CssTouchAction.java, org/w3c/css/properties/css3/Css3Style.java, org/w3c/css/properties/css3/CssTouchAction.java
This change makes the CSS checker recognize the `touch-action` property and
check its value.
The checking behavior conforms to the definition in the Pointer Events spec at
https://w3c.github.io/pointerevents/#the-touch-action-css-property and to the
Compatibility spec’s definition at https://compat.spec.whatwg.org/#touch-action
for the additional value `pinch-zoom`.
Tests: https://github.com/w3c/css-validator-testsuite/pull/1
=> Allow the touch-action property & check it

org/w3c/css/servlet/CssValidator.java
This change makes the server (servlet) allow empty file-upload input and
empty text/direct-input from POST requests — including from requests
made with the HTTP POST API — and to respond with a success message.
That more closely aligns the POST handling with the existing GET
handling; e.g., https://jigsaw.w3.org/css-validator/validator?text=,
which allows the `text` query parameter to be empty, and treats such
content as conforming (because empty CSS documents are valid).
Fixes https://github.com/w3c/css-validator/issues/73. Thanks @niedzielski
=> Make server allow empty input from POST requests

org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/parser/analyzer/CssParserTokenManager.java
This change makes the CSS checker support all Unicode code points greater than
or equal to U+0080 wherever the CSS Syntax spec requires “non-ASCII code points”
to be allowed. https://drafts.csswg.org/css-syntax/#non-ascii-code-point
Fixes #82 Thanks @dd8 & @crazyx13th
=> Support all Unicode code points ≧ U+0080 per spec

scripts/w3c-validator.js
This change adds client-side form validation to the Web UI, to provide a better
user experience: Users get error messages for empty URI/upload/textarea input
directly in the Web UI before the frontend submits any request to the server.
The text used in the form-validation error message pop-ups/tooltips is copied
from the existing instructions in the (localized) HTML content fo the page. So
the form-validation error messages are shown in the appropriate user locale.
=> Handle empty URI/upload/textarea input in Web UI

org/w3c/css/parser/CssPropertyFactory.java
This change causes the `zoom` property to be handled as a vendor extension if
the option to treat vendor extensions as warnings is set.
The change is implemented by providing a new hook in the code where the names of
any other commonly-used non-standard properties can be added later (if any other
than `zoom` ever end up being judged appropriate for similar special treatment).
=> Treat the 'zoom' property as a vendor extension

org/w3c/css/css/StyleSheetGenerator.java, org/w3c/css/css/xhtml.properties, org/w3c/css/util/Messages.java, org/w3c/css/util/Messages.properties.en, style/results.css
This change causes curly quotation marks to be added around literals in the raw
error and warning messages (before the messages get passed to Velocity for
processing with the output-format-specific *.properties templates).
For non-"xhtml" output formats, the curly quotation marks are left as-is
(unprocessed) in the messages emitted to end users. But for the "xhtml" output
format, the curly quotation marks get changed into HTML `<code>` and `</code>`
tags, which causes their contents to get rendered in a monospace font.
Note: this change moves the HTML-escaping out of the xhtml.properties template
(`$esc.html`s added in f7766d87d) and back into the StyleSheetGenerator code
(making the existing `queryReplace()` method once again do the actual escaping).
This change also makes minor …
=> Put literals in messages in curly quotes/monospace

org/w3c/css/properties/css3/CssWordBreak.java
This change allows the `break-word` value for the `word-break` property,
per https://www.w3.org/TR/2017/WD-css-text-3-20170822/#word-break-property
=> Allow 'word-break: break-word'

org/w3c/css/properties/CSS3Properties.properties, org/w3c/css/properties/CSS3SVGProperties.properties, org/w3c/css/properties/Media.properties, org/w3c/css/properties/css/CssUserSelect.java, org/w3c/css/properties/css3/Css3Style.java, org/w3c/css/properties/css3/CssUserSelect.java
This change makes the CSS checker recognize & check the `user-select` property.
The checking behavior conforms to the definition in Basic User Interface Module
Level 4 at https://www.w3.org/TR/2017/WD-css-ui-4-20171222/#propdef-user-select.
Fixes https://github.com/w3c/css-validator/issues/54. Thanks @nb000 & @cvrebert
=> Allow the user-select property & check it

org/w3c/css/selectors/PseudoFactory.java
This change allows the pseudo-classes defined in the HTML spec at
https://html.spec.whatwg.org/multipage/semantics-other.html#pseudo-classes
and as defined in https://fullscreen.spec.whatwg.org/#:fullscreen-pseudo-class,
the `fullscreen` pseudo-class.
Addresses https://github.com/validator/validator/issues/588 Thanks @zimorodokan
=> Allow pseduo-classes defined in HTML & Fullscreen

org/w3c/css/util/Messages.properties.en, org/w3c/css/util/Messages.properties.fr, org/w3c/css/values/CssImage.java
Given a case like the following:
> background:linear-gradient(top, #dd5959 0%,#c15252 100%)
...this change causes the checker to emit the following message:
> The first argument to the linear-gradient function should be “to top”, not “top”
That message is more helpful to users in fixing the cause of the problem than
the message reported prior to this change, which was the following:
> “top” is not a color value
=> Refine error message for malformed linear-gradient

org/w3c/css/selectors/PseudoClassSelector.java, org/w3c/css/selectors/SelectorsList.java, org/w3c/css/util/Messages.properties.en
This change fixes a couple bugs in the error message that’s reported for the
case of a selector that appears after a pseudo-element selector, and adds a
method to check for user-action pseudo classes
The first bug fixed by this change is, given a case like `p::first-line.foo`,
the CSS checker previously would report the following message:
> The pseudo-element .foo can't appear here in the context CSS level <level>
That message was wrong for that case because `.foo` isn’t a pseudo-element.
So this change causes the checker to instead report the following message:
> The selector .foo can't appear after the pseudo-element selector ::first-line
The second bug fixed by the change is, given a case like `p::first-line:hover`,
the checker would emit the following message:
> The pseudo-element …
=> Fix message bugs for selector after pseudo-element

org/w3c/css/selectors/PseudoFactory.java
This change allows the `selection`, `placeholder` & `backdrop` pseudo-elements.
`selection` & `placeholder` are defined in CSS Pseudo-Elements Level 4:
https://www.w3.org/TR/2016/WD-css-pseudo-4-20160607/#selectordef-selection
https://www.w3.org/TR/2016/WD-css-pseudo-4-20160607/#selectordef-placeholder
`backdrop` is defined in the Fullscreen spec:
https://fullscreen.spec.whatwg.org/#::backdrop-pseudo-element
=> Pseudo-elements: selection, placeholder, backdrop

org/w3c/css/properties/svg/CssPointerEvents.java, org/w3c/css/util/Messages.properties.en, org/w3c/css/util/Messages.properties.fr
This change allows the `auto` value for the `pointer-events` property.
The `auto` value for `pointer-events` is used commonly in the wild — even though
it’s not defined as valid in any CSS specs — because support for it has been
implemented in browsers for more than 10 years now.
Details are in comments in https://bugzilla.mozilla.org/show_bug.cgi?id=380573
and https://webkit.org/specs/PointerEventsProperty.html is the spec which the
browsers implemented from.
=> Allow 'pointer-events: auto'

org/w3c/css/parser/CssFouffa.java, org/w3c/css/parser/CssPropertyFactory.java, org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj
This change causes vendor-prefixed media features to be handled in the same way
as other vendor extensions — so if the option to treat vendor extensions as
warnings is set, messages about vendor-prefixed media features will be emitted
as warnings rather than as errors.
=> Treat prefixed media features as vendor extensions

org/w3c/css/css/CssValidator.java, org/w3c/css/index/validator.vm, validator.html.bg, validator.html.cs, validator.html.de, validator.html.el, validator.html.en, validator.html.es, validator.html.fa, validator.html.fr, validator.html.hi, validator.html.hu, validator.html.it, validator.html.ja, validator.html.ko, validator.html.nl, validator.html.pl-PL, validator.html.pt-BR, validator.html.ro, validator.html.ru, validator.html.sv, validator.html.uk, validator.html.zh-cn
This change makes the CSS3 + SVG profile the default profile in the Web UI and
in command-line checker. It also sets the TreatVendorExtensionsAsWarnings option
for the command-line checker to “true” by default (which the same default the
Web UI already uses).
=> Make CSS3+SVG the default profile

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/util/Messages.properties.en, org/w3c/css/util/Messages.properties.fr
This change causes the `0\0` value to be handled as a vendor extension if the
option to treat vendor extensions as warnings is set.
=> Treat 'min-width:0\0' hack as a vendor extension

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/Makefile, org/w3c/css/parser/analyzer/patch.star-property-hack
This change makes the parser gracefully handle cases like `*zoom: 1` where a CSS
identifier is prefixed with an asterisk (the so-called “star property hack”).
Without this change, the parser “derails” into a state where it ends up
incorrectly emitting spurious errors about later valid CSS constructs.
If the option to treat vendor extensions as warnings is set, a vendor-
extension warning message is reported; otherwise, a parse error is reported.
This change is itself a hack in that it achieves its effect by patching the
generated CssParser.java code after it’s been built by running javacc on the
CssParser.jj source.
=> Make parser handle “star property hack” gracefully

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/parser/analyzer/CssParserConstants.java, org/w3c/css/parser/analyzer/CssParserTokenManager.java
This change makes the parser gracefully handle cases like `width: 650px !ie7`
(when some unexpected string is found where `!important` is expected). Without
this change, the parser “derails” into a state where it ends up incorrectly
emitting spurious errors about later valid CSS constructs.
If the option to treat vendor extensions as warnings is set, a vendor-
extension warning message is reported; otherwise, a parse error is reported.
=> Make parser handle false-important hack gracefully

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/parser/analyzer/CssParserConstants.java, org/w3c/css/parser/analyzer/CssParserTokenManager.java
This comes in two part, the first commit is about parsing the first character before a possible ident, the second one is ignoring the declaration after a warning was generated (otherwise, the stripped property  name could be validated).
=> Make parser handle “star property hack” and related hacks

org/w3c/css/parser/CssFouffa.java, org/w3c/css/parser/CssPropertyFactory.java, org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/parser/analyzer/CssParserConstants.java, org/w3c/css/parser/analyzer/CssParserTokenManager.java, org/w3c/css/util/Messages.properties.en, org/w3c/css/values/CssExpression.java, org/w3c/css/values/CssHashIdent.java, org/w3c/css/values/CssIdent.java, org/w3c/css/values/CssValue.java
When "Treat Vendor Extensions as warnings" is enabled, this PR makes most usages of the `\9` hack result in warnings instead of errors.
This addresses the following:
``` css
prop: value \9;
prop: value\9;
```
This PR unfortunately does not yet fix the specific case of:
``` css
prop: «number»«unit?»\9;
```
...because that will require fiddling with the parser grammar (viz. the `<DIMEN>` token).
Fixes part of #10.
=> Treat \9 legacy IE property hack as a vendor extension warning

org/w3c/css/properties/css3/CssBorderRadius.java, org/w3c/css/properties/svg/CssClipPath.java, org/w3c/css/util/Messages.properties.en
This change brings `clip-path` checking a bit closer into alignment with the
requirements in https://drafts.fxtf.org/css-masking-1/#the-clip-path.
Even with this change, the checker still doesn’t recognize circle(), ellipse()
or polygon() values for clip-path, but it does now recognize inset() values —
with the limitation of not yet recognizing the `round <‘border-radius’>`
optional argument.
=> Align clip-path checking more closely with spec

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj
This change causes any TokenMgrError thrown in attributeDeclarations()
in the parser code to be caught and re-thrown as a ParseException so
that is gets reported as an error along with other errors.
Without this change, if parseStyleAttribute() is called from client code
on a case like one of the following:
<div id="myGallery" style="background:#;width:100%;">
<div .="" br="" div="" style="\">
...that is, with a syntax error, then a TokenMgrError is thrown but
never caught in any other part of the code. So it just becomes an
unhandled exception that without this change the client code would
otherwise have to write its own handling for.
The Web-based checker apparently has other code higher up for catching
that TokenMgrError and handling it. And of course handling for it could
be added to …
=> Catch TokenMgrError in attributeDeclarations()

scripts/w3c-validator.js
This change refines the client-side form-validation code added in
27ccde0 to add feature-detection for .reportValidity() and to not use it
in browsers that don’t support it (IE and Edge prior to Edge 17).
Fixes https://github.com/w3c/css-validator/issues/162 Thanks @IanC311
=> Deal with IE/Edge lack of reportValidity support

org/w3c/css/parser/CssFouffa.java, org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj
This change adds line and column numbers to all CssError instances created in
the parser code. Without this change, consuming/client code has no way to
isolate/pinpoint/extract/highlight the specific cause of some errors.
=> Add line+column numbers to all CssError in parser

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj
This change causes at-rules nested within other at-rules to be handled without
causing unexpected errors.
Fixes https://github.com/w3c/css-validator/issues/44
Fixes https://github.com/w3c/css-validator/issues/72
=> Allow nested at-rules

org/w3c/css/properties/CSS3Properties.properties, org/w3c/css/properties/CSS3SVGProperties.properties, org/w3c/css/properties/Media.properties, org/w3c/css/properties/css/CssScrollBehavior.java, org/w3c/css/properties/css3/Css3Style.java, org/w3c/css/properties/css3/CssScrollBehavior.java
This change makes the checker recognize & check the `scroll-behavior`
property.
The checking behavior conforms to the definition in the CSSOM View spec:
https://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#smooth-scrolling
=> Allow the scroll-behavior property & check it

org/w3c/css/properties/CSS3Properties.properties, org/w3c/css/properties/CSS3SVGProperties.properties, org/w3c/css/properties/Media.properties, org/w3c/css/properties/css/CssTextSizeAdjust.java, org/w3c/css/properties/css3/Css3Style.java, org/w3c/css/properties/css3/CssTextSizeAdjust.java
This change makes the CSS checker recognize & check the `text-size-adjust`
property.
The checking behavior conforms to the definition in the Mobile Text Size
Adjustment spec at https://drafts.csswg.org/css-size-adjust/
=> Allow the text-size-adjust property & check it

org/w3c/css/properties/CSS3Properties.properties, org/w3c/css/properties/CSS3SVGProperties.properties, org/w3c/css/properties/css/CssBackgroundPositionX.java, org/w3c/css/properties/css/CssBackgroundPositionY.java, org/w3c/css/properties/css3/Css3Style.java, org/w3c/css/properties/css3/CssBackgroundPositionX.java, org/w3c/css/properties/css3/CssBackgroundPositionY.java
Those properties are not yet in WD, but widely supported and seen in the wild, hence implemented against the edcopy (nov 2017).
=> background-position-[xy]

org/w3c/css/parser/analyzer/CssParser.java, org/w3c/css/parser/analyzer/CssParser.jj, org/w3c/css/parser/analyzer/CssParserConstants.java, org/w3c/css/parser/analyzer/CssParserTokenManager.java
This change prevents `-moz-calc(...)` and `-webkit-calc(...)` from
causing a parse error (which they otherwise do without this change) and
instead makes the code handle them as vendor extensions.
=> Treat -moz-calc/-webkit-calc as vendor extensions

org/w3c/css/properties/css3/CssMixBlendMode.java
This change fixes a typo in the code that caused the `color-burn` and
`color-dodge` values for `background-blend-mode` and `mix-blend-mode` to
be disallowed.
Closes https://github.com/w3c/css-validator/issues/179 Thanks @ajhoddinott
=> Fix typo that disallowed color-burn & color-dodge

build.xml
This change causes the velocity-tools jar file to be downloaded from the Central Repository (aka Maven Central) rather than from the www.apache.org site — because trying to download from the www.apache.org site results in frequent failures, particularly in Travis CI.
Note that this also causes the velocity-tools-2.0.jar file to be downloaded instead of the velocity-tools-generic-2.0.jar file — because the velocity-tools-generic-2.0.jar file isn’t available from Maven Central, and the velocity-tools-2.0.jar file has a superset of the classes in the velocity-tools-generic-2.0.jar file.
=> Download velocity-tools from Maven Central

build.xml
This change makes the download URL for the tagsoup jar file consistent with the other download URLs in build.xml (which use repo1.maven.org).
=> Make tagsoup download URL consistent with others

org/w3c/css/properties/css3/CssWordBreak.java
This change causes a specific *“The value 'break-word' is deprecated”* message to be reported. That aligns with the fact that the current CSS Text 3 spec now defines `break-word` as recognized `word-break` value:
https://drafts.csswg.org/css-text-3/#word-break-property
> Value:     normal | keep-all | break-all | break-word
...however, the spec also states:
> For compatibility with legacy content, the word-break property also
> supports a deprecated break-word keyword. When specified, this has the
> same effect as word-break: normal and overflow-wrap: anywhere,
> regardless of the actual value of the overflow-wrap property. However,
> the break-word keyword is not appropriate for newly-written style
> sheets. Authors must not use it.
=> Report a specific error for word-break: break-word

org/w3c/css/properties/css2/font/FontFamily.java
When a font-family includes spaces, it needs to be enclosed in quotes - e.g. `font-family: 'Open Sans'`.
This pull request removes adding another pair of quotes to already quoted strings.
Example: https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DOpen%2BSans&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=de
Input: 
```css
@font-face {
font-family: 'Open Sans';
...
}
```
Output (notice the additional double quotes at `'Open Sans'`):
```css
@font-face {
font-family : "'Open Sans'";
...
} 
```
=> FontFamily.convertString() double-escapes already escaped strings

org/w3c/css/values/CssURL.java
Previously, `CSSUrl.value` was stored verbatim, including any quotes around the actual value in `url( ... )`.
As `.value` is also used in `getURL()`, the resulting resolved URL included those quotes, which is wrong.
Example:
```css
* {background: url("file.png");
```
With a base of `http://www.example.org`, the result from `getURL()` was `http://www.example.org/"file.png"`.
This pull request modifies `CSSUrl` to remove balanced quotes from the input value before it is stored.
Admittedly, it has the side effect of removing the quotes also from the output of `toString()`, but they are optional and not needed anyways.
=> CSSUrl, remove quotes from the URL kept in .value

org/w3c/css/atrules/css/media/MediaFeature.java, org/w3c/css/atrules/css3/media/MediaDeviceAspectRatio.java, org/w3c/css/atrules/css3/media/MediaDeviceHeight.java, org/w3c/css/atrules/css3/media/MediaDeviceWidth.java, org/w3c/css/util/Messages.properties.en
When the CSS3 profile is selected, this change causes an error to be emitted for the following deprecated media features: device-aspect-ratio, device-height, device-width — as well as for their corresponding min- and max- prefixed versions.
https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#mf-deprecated states:
> The following media features are deprecated. They kept for backward
> compatibility, but are not appropriate for newly written style sheets.
> Authors must not use them.
Otherwise, without this change, no messages (not even warnings) are reported for the (mis)use of those media features.
=> Emit error for deprecated media features

org/w3c/css/atrules/css3/AtRuleMedia.java
When the CSS3 profile is selected, this change makes the CSS checker report an error if any deprecated media types are used — per the normative requirements in the current Media Queries spec:
https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#media-types
> ...the following deprecated media types are defined. Authors must not
use these media types: tty, tv, projection, handheld, braille, embossed, aural
Otherwise, without this change, only a warning (rather than an error) is reported.
=> Make deprecated media types an error (not warning)

org/w3c/css/parser/CssPropertyFactory.java
A CSS of:
```css
.inlineCss{text-decoration-style: initial}
```
triggers the following exception at `CssParser` line 5225:
```java
// Did the property recognize all values in the expression ?
if (!values.end() && ac.getMedium() == null) {
addError(new InvalidParamException("unrecognize", "", ac),
values);
```
Interestingly, I can not reproduce this on the public Jigsaw service, but in a direct call to `StyleSheetParser`:
> org.w3c.css.parser.CssParseException: Zu viele Werte oder die Werte werden nicht erkannt
> 	at org.w3c.css.parser.analyzer.CssParser.addError(CssParser.java:439)
> 	at org.w3c.css.parser.analyzer.CssParser.declaration(CssParser.java:5225)
> 	at org.w3c.css.parser.analyzer.CssParser.declarations(CssParser.java:3925)
> 	at …
=> Fix CssPropertyFactory to properly consume "initial" token

org/w3c/css/util/Messages.properties.zh-cn
There are some Chinese translations that are difficult to understand and feel like machine translations, so I made some adjustments. There are other places where there are problems and I will raise new PRs in the future.
=> Fix Chinese translation

org/w3c/css/atrules/css3/media/MediaPrefersContrast.java
prefers-contrast now accepts "less", "more", and "custom" rather than
"low", "high", and "forced".
Closes #363
=> Update prefers-contrast to match spec changes

org/w3c/css/values/CssANPlusB.java
Consider the following example:
```
.foo:nth-child(2){
margin-top: 2px;
}
```
The validator parses a null-byte before the number (2), because no operand is specified. This caused that the browsers couldn't understand the style.
=> BUGFIX for null-byte at nth-child selectors

org/w3c/css/css/StyleSheetParser.java
This change adds an optional `isPreprocessed` boolean parameter to the `StyleSheetParser()` constructor; if the value of that parameter is true, the steps from https://drafts.csswg.org/css-syntax/#input-preprocessing for preprocessing the input stream are skipped — so `UnescapeFilterReader()` is not called.
This is useful in a context where the input stream has already been preprocessed — for example, if the contents of the stylesheet being parsed are from an HTML document that has already been parsed by a conformant HTML parser (which is the case, for example, when the https://github.com/validator/validator HTML checker calls the code).
=> Allow preprocessing of the input stream to be skipped

org/w3c/css/util/UnescapeFilterReader.java
This PR fixes #383, as an alternative to #385.
This change drops the code for replacing surrogate code points from our implementation of “filter code points” from “Preprocessing the input stream” at https://drafts.csswg.org/css-syntax/#css-filter-code-points
I’ve also opened https://github.com/w3c/csswg-drafts/pull/7997 with a patch for updating that part of the CSS Syntax spec to add a clarifying note.
https://github.com/w3c/csswg-drafts/issues/3307#issuecomment-442198338 notes that the only way to produce a unpaired lone surrogate code point in CSS content is by directly assigning a DOMString with one in it via an OM operation; in other words, by manipulating a document using, e.g., `document.styleSheets` in JavaScript to insert a surrogate code point into the document. See the tests at …
=> Don’t do surrogate replacement when preprocessing input stream

org/w3c/css/css/StyleSheetGenerator.java
This option didn't do anything, because the value it set (showCSS) wasn't considered when generating the output.
=> Fix non-functional --printCSS/-p option

org/w3c/css/properties/CSS3Properties.properties, org/w3c/css/properties/css/CssRotate.java, org/w3c/css/properties/css/CssScale.java, org/w3c/css/properties/css/CssTranslate.java, org/w3c/css/properties/css3/Css3Style.java, org/w3c/css/properties/css3/CssBackfaceVisibility.java, org/w3c/css/properties/css3/CssPerspective.java, org/w3c/css/properties/css3/CssPerspectiveOrigin.java, org/w3c/css/properties/css3/CssRotate.java, org/w3c/css/properties/css3/CssScale.java, org/w3c/css/properties/css3/CssTransform.java, org/w3c/css/properties/css3/CssTransformStyle.java, org/w3c/css/properties/css3/CssTranslate.java
align with https://www.w3.org/TR/2021/WD-css-transforms-2-20211109/
=> Transform 2

build.xml, org/w3c/css/index/IndexGenerator.java, org/w3c/css/index/TranslationTableGenerator.java
Same as #453 but this one keeps the html files (and doesn't delete them in the `clean` task) although I don't really see why they should be kept since:
- if the generated file doesn't exists it is created anyway by the servlet
- if the file is older than the template it will be regenerated by the servlet
However, in both cases, this requires the servlet to have write permission on their folder.
I can suppose this can be useful for jigsaw, and maybe as deployed war (on tomcat/jetty...), but this reveals bug https://github.com/w3c/css-validator/issues/451
Checking whether regeneration is required using the timestamp doesn't really make sense in a git repo as the timestamps of the commit are not kept&restored from the commit date IIRC. But on a deployed app using the timestamp makes sense. …
=> Generate html files at build time (keeps HTML)
