- build.xml
> build.xml: tabs => spaces

- CONTRIBUTING.md
> Add build instructions

- org/w3c/css/util/Messages.properties.zh-cn
The translation isn't perfect, but I did not come up with a better one for the time being...
> zh-cn translation of #93

- org/w3c/css/properties/css3/CssPosition.java
Per https://www.w3.org/TR/css-position-3/#valdef-position-sticky
Fixes https://github.com/w3c/css-validator/issues/127. Thanks @cvrebert
> Allow 'position: sticky' per Positioned Layout 3

- org/w3c/css/properties/CSS3SVGProperties.properties
- org/w3c/css/properties/SVGProperties.properties
- org/w3c/css/properties/css/CssMaskComposite.java
- org/w3c/css/properties/svg/CssMaskComposite.java
- org/w3c/css/properties/svg/SVGStyle.java
> mask-composite 

- org/w3c/css/properties/CSS3SVGProperties.properties
- org/w3c/css/properties/SVGProperties.properties
- org/w3c/css/properties/css/CssMaskImage.java
- org/w3c/css/properties/svg/CssMaskImage.java
- org/w3c/css/properties/svg/SVGStyle.java
per https://www.w3.org/TR/2014/CR-css-masking-1-20140826/#propdef-mask-image (see #151)
> mask-image

- org/w3c/css/parser/CssPropertyFactory.java
- org/w3c/css/util/Messages.properties.en
- org/w3c/css/util/Messages.properties.fr
This may need some caching if proven too cpu intensive but let's not over engineer this.
> matching property name in case of typo

- org/w3c/css/properties/css1/CssFont.java
- org/w3c/css/properties/css2/CssFont.java
- org/w3c/css/properties/css21/CssFont.java
- org/w3c/css/properties/css3/CssFont.java
- org/w3c/css/util/Messages.properties.en
- org/w3c/css/util/Messages.properties.fr
Addresses https://github.com/validator/validator/issues/661
> Improve message for misplaced system-font keyword

- org/w3c/css/util/Messages.properties.zh-cn
Note that there might be other remaining, or quote that should be modified, hence requesting review.
> collapsing meaningless spaces per discussion with @xfq

- org/w3c/css/properties/CSS3Properties.properties
- org/w3c/css/properties/css/CssTransformBox.java
- org/w3c/css/properties/css3/Css3Style.java
- org/w3c/css/properties/css3/CssTransform.java
- org/w3c/css/properties/css3/CssTransformBox.java
- org/w3c/css/properties/css3/CssTransformOrigin.java
See https://www.w3.org/TR/2019/CR-css-transforms-1-20190214/#property-index
Note that some definitions from transforms-2 remain but were not updated.
> up-to-date with 20190214 transforms-1 CR.

- org/w3c/css/atrules/css/AtRuleImport.java
- org/w3c/css/css/CssRuleList.java
Please add public methods  allow access to important properties of AtRuleImport and CSSRuleList.
> New public get() Methods in CSSRuleList and AtRuleImport and CSSRuleList

- build.xml
Resolve can't get jar file. (Got Build Fail with the http).
> Build Failed with Http

- org/w3c/css/util/InvalidParamException.java
- org/w3c/css/util/Messages.properties.en
- org/w3c/css/util/Warning.java
> allow messages for errors and warning to modify the order of arguments

- org/w3c/css/properties/CSS3Properties.properties
- org/w3c/css/properties/css/CssColorScheme.java
- org/w3c/css/properties/css3/Css3Style.java
- org/w3c/css/properties/css3/CssColorScheme.java
> color-scheme property

- org/w3c/css/properties/CSS3Properties.properties
- org/w3c/css/properties/css/CssOverflowAnchor.java
- org/w3c/css/properties/css3/Css3Style.java
- org/w3c/css/properties/css3/CssOverflowAnchor.java
per https://www.w3.org/TR/2020/WD-css-scroll-anchoring-1-20201111/
> scroll-anchoring-1

- org/w3c/css/parser/analyzer/CssParser.java
- org/w3c/css/parser/analyzer/CssParser.jj
- org/w3c/css/parser/analyzer/CssParserConstants.java
- org/w3c/css/properties/css3/CssBackgroundColor.java
- org/w3c/css/properties/css3/CssColor.java
> Css variable

- org/w3c/css/parser/analyzer/CssParser.java
- org/w3c/css/parser/analyzer/CssParser.jj
merge latest fix to address live validator issue on var() parsing
> Css variable parsing

- org/w3c/css/parser/analyzer/CssParser.java
- org/w3c/css/parser/analyzer/CssParser.jj
- org/w3c/css/properties/css3/CssAccentColor.java
- org/w3c/css/properties/css3/CssAlignContent.java
- org/w3c/css/properties/css3/CssAlignItems.java
- org/w3c/css/properties/css3/CssIsolation.java
- org/w3c/css/values/CssImage.java
Like what was done with CssColor (See 78c20e05949dec27892832e2ed23c9cf11de6d85 )
This should address https://github.com/validator/validator/issues/1224
> css image fix for css variable

- org/w3c/css/properties/CSS3Properties.properties
- org/w3c/css/properties/css/CssOverscrollBehavior.java
- org/w3c/css/properties/css/CssOverscrollBehaviorBlock.java
- org/w3c/css/properties/css/CssOverscrollBehaviorInline.java
- org/w3c/css/properties/css/CssOverscrollBehaviorX.java
- org/w3c/css/properties/css/CssOverscrollBehaviorY.java
- org/w3c/css/properties/css3/Css3Style.java
- org/w3c/css/properties/css3/CssOverscrollBehavior.java
- org/w3c/css/properties/css3/CssOverscrollBehaviorBlock.java
- org/w3c/css/properties/css3/CssOverscrollBehaviorInline.java
- org/w3c/css/properties/css3/CssOverscrollBehaviorX.java
- org/w3c/css/properties/css3/CssOverscrollBehaviorY.java
> Overscroll 1

- org/w3c/css/util/Messages.properties.pl-PL
> Corrections in the encoding of characters ą, ś, ź

- org/w3c/css/util/Messages.properties.fr
Fix a typo in french translations
laur -> leur
> Fix a typo error

- org/w3c/css/properties/css3/CssFontSizeAdjust.java
per https://www.w3.org/TR/2024/WD-css-fonts-5-20240206/#propdef-font-size-adjust
This addresses #435
> font-size-adjust update

- org/w3c/css/util/Messages.properties.pl-PL
Completing missing translations and correcting existing ones. The file has been compared with the English file and is now complete.
Note: I forgot about my earlier PR, because I had the finished file locally on disk.
I built my version for myself and forgot to prepare the commit.
> Full update Messages.properties.pl-PL
